# Рабочая тетрадь №2. Основы Phyton. Библиотеки
###  Алхимов Василий Юрьевич

Цель машинного обучения - анализ данных.
Данные - зарегистрированная информация; представление фактов понятий или инструкций в форме, приемлемой для общения,
интерпретации, или обработки человеком или с помощью автоматических средств (ISO/IEC/IEEE 24765-2010)

___Данные в машинном обучении___ - это представление информации об исследуемой задаче в виде множеств исследуемых
объектов и множеств их характеристик на основе которых строятся модели, разрабатываются подходы, методы и алгоритмы
анализа для принятия решений.

Качество данных - важный аспект машинного обучения.
Для Аналитика (Data Scientist, Data Analyst, Data Mining Engineer) очень важно обладать правильными данными, что
гарантирует эффективность обработки и построении прогнозов.

#### ***Основные требования к данным:***
* Доступность
* Точность
* Полнота
* Непротиворечивость
* Однозначность
* Релевантность
* Надежность
* Своевременность
* Взаимосвязанность

Остановимся на основных этапах решения задач машинного обучения.
Этапы решения задач машинного обучения:
1. Постановка задачи
2. Сбор и подготовка данных
3. Предобработка данных и выделение ключевых признаков
4. Выбор алгоритмов машинного обучения
5. Обучение модели(моделей)
6. Оценка качества
7. Эксплуатация модели

При подготовке данных можно применять следующие операции:

* ___структурирование___ - приведение данных к табличному (матричному виду);
* ___заполнение пропусков___;
* ___отбор___ - исключение записей с отсутствующими или некорректными значениями,
если нет возможности заполнения и устранения противоречивости;
* ___нормализация___ – приведение числовых значений к определенному
диапазону, например к диапазону 0...1;
* ___кодирование___ – это представление категориальных данных в числовой
форме.


## Библиотека NumPy
NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
* pip install numpy

Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:

* import numpy as np

Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray).
Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
ndarray.ndim - число измерений (чаще их называют "оси") массива.
ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

### 1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
Задача:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами
3. Создать вектор размера 10, заполненный заданным числом
4. Создать вектор со значениями от 10 до 49

In [6]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример
Задача:
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение

In [8]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin,Zmax,Zmean)

0.014087290432437394 0.983205137331214 0.5073697960832422


### 1.2.4 Пример
Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами

In [10]:
import numpy as np
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Задача:
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [11]:
import numpy as np
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Задача:
Отсортировать массив

In [12]:
import numpy as np
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [4]:
import numpy
matrix = numpy.tile(numpy.array([[0,1],[1,0]]), (4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для
создания необходимо использовать функцию arrange.

In [5]:
import numpy
matrix = numpy.zeros((5,5))
matrix += numpy.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями

In [7]:
import numpy
matrix = numpy.random.random((3,3,3))
print(matrix)

[[[0.99691636 0.29167697 0.9207245 ]
  [0.66751182 0.1005116  0.18909067]
  [0.37496118 0.97138905 0.59440898]]

 [[0.45312029 0.53040129 0.20992552]
  [0.99044287 0.66737065 0.08607143]
  [0.98077817 0.96417739 0.64487923]]

 [[0.95862089 0.26500175 0.78391215]
  [0.94946916 0.33308287 0.5050708 ]
  [0.64148689 0.57053717 0.11794329]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [17]:
import numpy
matrix = numpy.ones((4,4))
matrix[1:-1,1:-1] = 0
print(matrix)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию

In [38]:
import numpy
#print(*sorted(numpy.arange(1,10),reverse=True))
print(numpy.arange(1,10)[::-1])

[9 8 7 6 5 4 3 2 1]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [46]:
import numpy
m = numpy.matrix([[1,1],[1,1]])
print(f'Matrix is:\n {m}')
print(f'Shape: {numpy.shape(m)}')
print(f'Size: {numpy.size(m)}')
print(f'Dimension: {len(numpy.shape(m))}')

Matrix is:
 [[1 1]
 [1 1]]
Shape: (2, 2)
Size: 4
Dimension: 2


## Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.

___Библиотека pandas___ – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.

___Библиотека pandas___ присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:

* pip install pandas

Для импорта библиотеки используйте команду:
* import pandas as pd

Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.

___Series___ – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.

___DataFrame___ – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.

### 2.2.1 Пример
Задача:
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [13]:
import pandas as pd
lst = [1,2,3,4,5]
d = {'a':1,'b':2,'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### 2.2.2 Пример
Задача:
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [26]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5], ['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[1:])

1
5
1    4
2    3
3    2
4    1
dtype: int64


### 2.2.3 Пример
Задача:
Создайте новый фрейм данных.

In [27]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
Задача:
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/tit
anic.csv

In [10]:
import pandas as pd
# Создать URL-адрес
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
# показать пять строк


dataframe["Age"].median()
dataframe["Age"] = dataframe["Age"].fillna(28)
dataframe.head(40)
#dataframe.describe()

Name PClass    Age     Sex  \
0                       Allen, Miss Elisabeth Walton    1st  29.00  female   
1                        Allison, Miss Helen Loraine    1st   2.00  female   
2                Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3      Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                      Allison, Master Hudson Trevor    1st   0.92    male   
5                                 Anderson, Mr Harry    1st  47.00    male   
6                   Andrews, Miss Kornelia Theodosia    1st  63.00  female   
7                             Andrews, Mr Thomas, jr    1st  39.00    male   
8       Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female   
9                             Artagaveytia, Mr Ramon    1st  71.00    male   
10                         Astor, Colonel John Jacob    1st  47.00    male   
11  Astor, Mrs John Jacob (Madeleine Talmadge Force)    1st  19.00  female   
12                      Aubert, Mrs Leontine Pauline    1st  28.00  female   
13                          Barkworth, Mr Algernon H    1st  28.00    male   
14                                Baumann, Mr John D    1st  28.00    male   
15    Baxter, Mrs James (Helene DeLaudeniere Chaput)    1st  50.00  female   
16                           Baxter, Mr Quigg Edmond    1st  24.00    male   
17                               Beattie, Mr Thomson    1st  36.00    male   
18                      Beckwith, Mr Richard Leonard    1st  37.00    male   
19   Beckwith, Mrs Richard Leonard (Sallie Monypeny)    1st  47.00  female   
20                              Behr, Mr Karl Howell    1st  26.00    male   
21                                Birnbaum, Mr Jakob    1st  25.00    male   
22                            Bishop, Mr Dickinson H    1st  25.00    male   
23            Bishop, Mrs Dickinson H (Helen Walton)    1st  19.00  female   
24           Bjornstrm-Steffansson, Mr Mauritz Hakan    1st  28.00    male   
25                       Blackwell, Mr Stephen Weart    1st  45.00    male   
26                                   Blank, Mr Henry    1st  39.00    male   
27                            Bonnell, Miss Caroline    1st  30.00  female   
28                           Bonnell, Miss Elizabeth    1st  58.00  female   
29                           Borebank, Mr John James    1st  28.00    male   
30                           Bowen, Miss Grace Scott    1st  45.00  female   
31                        Bowerman, Miss Elsie Edith    1st  22.00  female   
32                                Bradley, Mr George    1st  28.00    male   
33                            Brady, Mr John Bertram    1st  41.00    male   
34                                 Brandeis, Mr Emil    1st  48.00    male   
35                          Brewe, Dr Arthur Jackson    1st  28.00    male   
36  Brown, Mrs James Joseph (Margaret Molly" Tobin)"    1st  44.00  female   
37     Brown, Mrs John Murray (Caroline Lane Lamson)    1st  59.00  female   
38    Bucknell, Mrs William Robert (Emma Eliza Ward)    1st  60.00  female   
39                  Butt, Major Archibald Willingham    1st  45.00    male   

    Survived  SexCode  
0          1        1  
1          0        1  
2          0        0  
3          0        1  
4          1        0  
5          1        0  
6          1        1  
7          0        0  
8          1        1  
9          0        0  
10         0        0  
11         1        1  
12         1        1  
13         1        0  
14         0        0  
15         1        1  
16         0        0  
17         0        0  
18         1        0  
19         1        1  
20         1        0  
21         0        0  
22         1        0  
23         1        1  
24         1        0  
25         0        0  
26         1        0  
27         1        1  
28         1        1  
29         0        0  
30         1        1  
31         1        1  
32         1        0  
33         0        0  
34       

### 2.2.5 Пример
Задача:
Пронализировать характеристики фрейма данных

Решение:

Одна из самых простых вещей, которые мы можем сделать после
загрузки данных, – это взглянуть на первые несколько строк с
помощью метода head. На последние строки можно посмотреть с
помощью функции tail. Мы также можем взглянуть на количество
строк и столбцов: dataframe.shape. Кроме того, используя метод
describe, мы можем получить описательную статистику для любых
числовых столбцов.

In [40]:
import pandas as pd
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

### 2.2.6 Пример

Задача:
Выберите индивидуальные данные или срезы фрейма данных.
Решение:
Для выбора одной или нескольких строк либо значений использовать
методы 1ос или iloc

In [2]:
import pandas as pd
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

### 2.2.7 Пример

Задача:
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из
пассажиров первого класса.

In [3]:
import pandas as pd
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

### 2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [3]:
import pandas
import numpy

a = pandas.Series([2, 4, 6, 8])
b = pandas.Series([1, 3, 5, 7])

print(numpy.linalg.norm(a-b)) #sum((a - b)**2)**.5

2.0


### 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из
него фрейм данных (например, коллекцию фреймов данный можно
найти здесь: https://github.com/akmand/datasets)

In [33]:
import pandas
pandas.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/adult.csv')

age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
4       28           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
45217   33           Private             13       Never-married   
45218   39           Private             13            Divorced   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race  gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White    Male              40   
1        Exec-managerial        Husband  White    Male              13   
2      Handlers-cleaners  Not-in-family  White    Male              40   
3      Handlers-cleaners        Husband  Other    Male              40   
4         Prof-specialty           Wife  Other  Female              40   
...                  ...            ...    ...     ...             ...   
45217     Prof-specialty      Own-child  White    Male              40   
45218     Prof-specialty  Not-in-family  White  Female              36   
45219     Prof-specialty        Husband  White    Male              50   
45220       Adm-clerical      Own-child  Other    Male              40   
45221    Exec-managerial        Husband  White    Male              60   

      native_country  capital income_status  
0      United-States     2174         <=50K  
1      United-States        0         <=50K  
2      United-States        0         <=50K  
3      United-States        0         <=50K  
4              Other        0         <=50K  
...              ...      ...           ...  
45217  United-States        0         <=50K  
45218  United-States        0         <=50K  
45219  United-States        0         <=50K  
45220  United-States     5455         <=50K  
45221  United-States        0          >50K  

[45222 rows x 12 columns]

### 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7
+ Пронализировать характеристики фрейма данных
+ Выберите индивидуальные данные или срезы фрейма данных.
+ Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из
пассажиров первого класса.


In [2]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/adult.csv')
print('analyze \n')
df.head(2)
df.tail(3)
df.describe()

analyze 



age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [53]:
df = pandas.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/adult.csv')
print('\n slice iloc \n')
df.iloc[1:6] # не включает конец
# df.loc[1:6] # включает конец


 slice iloc 



age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   
5   37           Private             14  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   
5    Exec-managerial           Wife  White  Female              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K  
5  United-States        0         <=50K

In [38]:
df = pandas.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/adult.csv')
print('\n new format\n')
df3 = df[df['race'] == 'White'].head(2)
df3


 new format



age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

## Работа с числовыми данными

Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).

Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.

Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.

На практике наиболее распространены следующие методы
нормализации признаков:

* Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
* Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

### нормализация по методу ___минимакс___

Xnorm = (X - Xmin)/(Xmax - Xmin)
-------------------------
### Z-масштабирование
z = (x - μ)/δ
-------------------------
При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

### 3.2.1. Пример
Задача:
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [4]:
# загрузить библиотеки
import numpy as np
from sklearn import preprocessing
# создать признак
feature = np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])
# создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))
# прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)
# показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2. Пример
Задача:
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1
Решение:

In [6]:
x = np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])
# создать шкалироващик
scaler = preprocessing.StandardScaler()
# преобразовать признак
standardized = scaler.fit_transform(x)
# показать призник
standardized

#Мы можем увидеть эффект стандартизации, обратившись к среднему значению и стандартному
#отклонению результата нашего решения:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:",standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


### 3.2.3. Пример
Задача:
Дан фрейм данных

dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})

Необходимо масштабировать его числовые столбцы.

In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
dfTest[['A','B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2 Задание

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [51]:
import pandas as pd
from sklearn import preprocessing
x = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scalerZ = preprocessing.StandardScaler()
x[["sepal_length_cm"]] = scaler.fit_transform(x[["sepal_length_cm"]])
x[["sepal_width_cm"]] = scalerZ.fit_transform(x[["sepal_width_cm"]])
x

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

## Доп задание

In [4]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[15],[16],[50],[100],[10]])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.05555556],
       [0.06666667],
       [0.44444444],
       [1.        ],
       [0.        ]])

In [5]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[15],[16],[50],[100],[10]])

minmax_scale = preprocessing.StandardScaler()

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[-0.68206979],
       [-0.65267023],
       [ 0.34691481],
       [ 1.8168928 ],
       [-0.82906759]])